"""avatar_on_delete

Revision ID: 0005
Revises: 0004
Create Date: 2023-12-20 11:24:02.802737

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("posts_avatar_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(None, "posts", "avatars", ["avatar_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_avatar_id_fkey", "posts", "avatars", ["avatar_id"], ["id"])
    # ### end Alembic commands ###
